const {exec, pwd} = require('shelljs')
const {existsSync, mkdirSync, writeFileSync, rmdirSync, execSync} = require('fs')
const {randomBytes} = require('crypto')
const {join} = require('path')
const {copySync} = require('fs-extra')

require('dotenv').config()
const fs = require('fs')

exports.handler = async function main(event, context) {


    // const dir = './tempo';
    // if (!existsSync(dir)){
    //     mkdirSync(dir);
    // }
//     const dir = '/tmp';
    const website = 'next-customer-starter'

//     const config =
//         `import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Judith App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/next/src/public/favicon.ico" />
//       </Head>



//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
// `
//     writeFileSync(`/mnt/sites/testo.js`, config);

//     writeFileSync(`/tmp/testo.js`, config);
    const bashcode = `
#!/bin/sh


cd /mnt/sites/app/${website}


npm run export


`

    const wd = pwd().stdout


    console.log(wd)
    // exec('npm run build', {async:true}).stdout

// //     setTimeout(() => {
    // exec('npm run export', {async:true}).stdout
// // }, 10000);

// //       setTimeout(() => {
// //     console.log('done exports')
// // }, 5000);

    const webdir = `/mnt/sites/app/${website}`
    // mkdirSync(webdir)


//   copySync(wd, webdir, function (err) {

//       console.log('copying files and foleders')
//         if (err) {
//             console.log('An error occured while copying the folder.')
//             return console.error(err)
//         }
//         console.log('Copy completed!')
//     })


    writeFileSync(`${webdir}/export.sh`, bashcode);
    exec(`chmod +x ${webdir}/export.sh` )

    var neration = exec(`${webdir}/export.sh`,{async:false}).stdout;
    console.log(neration)
    console.log('finished exporting?')





//     if (!existsSync(webdir)) {
//       await mkdirSync(webdir, {recursive: true})
//     console.log('folder created')

//     }
//     const source = `/mnt/sites/out`
//     copySync(source, webdir, function (err) {

//       console.log('copying files and foleders')
//         if (err) {
//             console.log('An error occured while copying the folder.')
//             return console.error(err)
//         }
//         console.log('Copy completed!')
//     })

//     if (existsSync(`/.next`)){
//       await rmdirSync(`/.next`, {recursive: true})
//     }

    // rmdirSync(source, {recursive: true})
    // rmdirSync(`${dir}/pages`, {recursive: true})
    // rmdirSync(`${dir}/public`, {recursive: true})
    // rmdirSync(`${dir}/styles`, {recursive: true})
    // rmdirSync(`${dir}/.next`, {recursive: true})
// exec(`${wd}/export.sh`,{async:true}).stdout;
}
